FROM debian:12.13-slim

RUN apt-get -q update && \
  apt-get -y install libapache2-mod-shib && \
  apt-get -y autoremove

COPY shibd.logger /etc/shibboleth/shibd.logger
COPY shibd-foreground /usr/local/bin
RUN chmod a+x /usr/local/bin/shibd-foreground

CMD ["shibd-foreground"]
