#!/bin/sh
set -e

NAME=shibd
SHIBSP_CONFIG=/etc/shibboleth/shibboleth2.xml
PIDFILE=/run/shibboleth/$NAME.pid

[ -d '/run/shibboleth' ] || mkdir -p '/run/shibboleth'
exec /usr/sbin/shibd -f -c $SHIBSP_CONFIG -p $PIDFILE -F
